class SKey:
    NOUN: str
    ADJ: str
    ADV: str
    VERB: str
    AUX: str
    MODAL: str
    PRON: str
    DET: str
    PREP: str
    CONJ: str
    COMPL: str
    GENDER: str
    STATIVE: str
    PROPER: str
    BROAD_NEG: str
    INTERR: str
    DEMONST: str
    INTRAN: str
    TRAN: str
    DITRAN: str
    LINK: str
    CPLXTRAN: str
    MOD_TYPE: str
    POSITION: str
    TYPE: str
    IRREG: str
    REG: str
    REGD: str
    GLREG: str
    UNCOUNT: str
    GCOUNT: str
    METAREG: str
    PLUR: str
    SING: str
    INV: str
    INV_PERIPH: str
    SINGULAR: str
    PLURAL: str
    INFINATIVE: str
    THIRD_PRES: str
    PAST: str
    PAST_PART: str
    PRES_PART: str
    PRESENT: str
    POSITIVE: str
    COMPARATIVE: str
    SUPERLATIVE: str
