from _typeshed import Incomplete

from nltk.sem import evaluate as evaluate

def parse_sents(
    inputs: Incomplete, grammar: Incomplete, trace: int = 0
) -> Incomplete: ...
def root_semrep(syntree: Incomplete, semkey: str = "SEM") -> Incomplete: ...
def interpret_sents(
    inputs: Incomplete,
    grammar: Incomplete,
    semkey: str = "SEM",
    trace: int = 0,
) -> Incomplete: ...
def evaluate_sents(
    inputs: Incomplete,
    grammar: Incomplete,
    model: Incomplete,
    assignment: Incomplete,
    trace: int = 0,
) -> Incomplete: ...
def demo_model0() -> None: ...
def read_sents(filename: Incomplete, encoding: str = "utf8") -> Incomplete: ...
def demo_legacy_grammar() -> None: ...
def demo() -> None: ...
