from _typeshed import Incomplete

class MinimalSet:
    def __init__(self, parameters: Incomplete | None = None) -> None: ...
    def add(
        self, context: Incomplete, target: Incomplete, display: Incomplete
    ) -> None: ...
    def contexts(self, minimum: int = 2) -> Incomplete: ...
    def display(
        self, context: Incomplete, target: Incomplete, default: str = ""
    ) -> Incomplete: ...
    def display_all(self, context: Incomplete) -> Incomplete: ...
    def targets(self) -> Incomplete: ...
