version: "1"

ignore:
  - .git
  - .tox
  - .venv
  - .vscode
  - tests/
  - htmlcov/
  - test_*.py
  - src/_vendor

rule_settings:
  enable:
    - default
    - google-python-style-guide
  disable:
    - no-relative-imports
    - do-not-use-staticmethod
    - docstrings-for-functions
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.13"
