[tool.poetry]
name = "vocab-tester"
version = "0.3.0-dev"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"
packages = [{ include = "python_src" }]

[tool.poetry.dependencies]
python = ">=3.2"
dill = "==0.3.4"
nltk = "==3.5"
lemminflect = "==0.2.3"
inflect = "==0.3.0"
lz4 = [
    { version = "==4.3.3", python = ">=3.8" },
    { version = "==4.0.0", python = "~3.7" },
    { version = "==3.1.9", python = ">=3.5,<3.7" },
    { version = "==2.2.1", python = "~3.4" },
    { version = "==0.13.0", python = "<3.4" },
]
aenum = "==3.1.15"
numpy = [
    { version = "==1.11.3", python = ">=3.2 <3.5" },
    { version = "==1.18.5", python = ">=3.5 <3.9" },
    { version = "==1.26.4", python = ">=3.9 <3.13" },
    { version = "==2.1.0", python = "~3.13" },
]

[tool.poetry.group.dev.dependencies]
# Only to be used with the latest version of python.
coconut = { version = "==3.1.2", python = ">=3.13" }
icecream = { version = "==2.1.3", python = ">=3.13" }
mypy = { version = "==1.11.2", python = ">=3.13" }
ruff = { version = "==0.7.0", python = ">=3.13" }
pytest = { version = "==8.3.3", python = ">=3.13" }
monkeytype = { version = "==23.3.0", python = ">=3.13" }
coverage = { version = "==7.6.3", python = ">=3.13" }
pytest-cov = { version = "==5.0.0", python = ">=3.13" }
pytest-sugar = { version = "==1.0.0", python = ">=3.13" }
codetiming = { version = "==1.4.0", python = ">=3.13" }
pytest-xdist = { version = "==3.6.1", python = ">=3.13" }
docstr-coverage = { version = "==2.3.2", python = ">=3.13" }
pydoctest = { version = "==0.2.1", python = ">=3.13" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
