[tool.poetry]
name = "vocab-tester"
version = "0.1.0"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
immutabledict = "^4.2.0"
dill = "^0.3.8"
nltk = "^3.8.1"
lemminflect = "^0.2.3"
spacy = "^3.7.5"


[tool.poetry.group.dev.dependencies]
icecream = "*"
autoimport = "*"
mypy = "*"
ruff = "*"
pytest = "*"
bpython = "^0.24"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = false
