[tool.poetry]
name = "vocab-tester"
version = "0.1.0"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"
packages = [{ include = "python_src" }]

[tool.poetry.dependencies]
python = "^3.12.5"
dill = "^0.3.8"
nltk = "^3.8.1"
lemminflect = "^0.2.3"
frozendict = "^2.4.4"
inflect = "^7.3.1"

[tool.poetry.group.dev.dependencies]
icecream = "*"
mypy = "*"
ruff = "*"
pytest = "*"
monkeytype = "^23.3.0"
coverage = "^7.6.1"
pytest-cov = "^5.0.0"
pytest-sugar = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false

[tool.ruff]
line-length = 79

[tool.mypy]
strict = true
warn_return_any = true
warn_unreachable = true
strict_equality = true
mypy_path = "mypy_stubs"
