[tool.poetry]
name = "vocab-tester"
version = "0.3.0-dev"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"
packages = [{ include = "python_src" }]

[tool.poetry.dependencies]
python = ">=3.8"
dill = "==0.3.8"
nltk = "==3.8.1"
lemminflect = "==0.2.3"
inflect = "==7.3.1"
numpy = [
    { version = "1.24.4", python = "~3.8" },
    { version = "1.26.4", python = ">=3.9 <3.13" },
    { version = "2.1.0", python = "~3.13" },
]

[tool.poetry.group.dev.dependencies]
icecream = "==2.1.3"
mypy = "==1.11.2"
ruff = "==0.6.4"
pytest = "==8.3.2"
monkeytype = "==23.3.0"
coverage = "==7.6.1"
pytest-cov = "==5.0.0"
pytest-sugar = "==1.0.0"
codetiming = "==1.4.0"
pytest-xdist = "==3.6.1"
docstr-coverage = "==2.3.2"
pydoctest = "==0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
unsafe-fixes = true


[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "UP009",
    "S101",
    "ERA001",
    "EXE001",
    "PLC0414",
    "EM102",
    "EM101",
    "TRY003",
    "ANN",
    "E501",
    "S403",
    "FURB101",
    "PTH123",
    "DOC502",
    "TID252",
    "D105",
    "D401",
    "S301",
    "CPY001",
    "PLR2004",
    "PLR0911",
    "C901",
    "PLR0912",
    "PLR0913",
    "COM812",
    "ISC001",
    "E",
    "W",
    "I",
    "FIX004",
]


[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 72

[tool.mypy]
disallow_untyped_defs = true
strict = true
warn_return_any = true
warn_unreachable = true
strict_equality = true
mypy_path = "mypy_stubs"
exclude = 'tests/.*'

[tool.coverage.run]
omit = ["tests/*"]

[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "if self\\.debug",

    "raise AssertionError",
    "raise NotImplementedError",

    "if 0:",
    "if __name__ == .__main__.:",

    "@(abc\\.)?abstractmethod",

    "if TYPE_CHECKING:",
]
