[tool.poetry]
name = "vocab-tester"
version = "0.3.0-dev"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"
packages = [{ include = "python_src" }]

[tool.poetry.dependencies]
python = ">=3.8"
dill = "==0.3.8"
nltk = "==3.9.1"
lemminflect = "==0.2.3"
inflect = "==7.4.0"
numpy = [
    { version = "1.24.4", python = "~3.8" },
    { version = "1.26.4", python = ">=3.9 <3.13" },
    { version = "2.1.0", python = "~3.13" },
]
coconut = "==3.1.2"

[tool.poetry.group.dev.dependencies]
icecream = "==2.1.3"
mypy = "==1.11.2"
ruff = "==0.6.8"
pytest = "==8.3.3"
monkeytype = "==23.3.0"
coverage = "==7.6.1"
pytest-cov = "==5.0.0"
pytest-sugar = "==1.0.0"
codetiming = "==1.4.0"
pytest-xdist = "==3.6.1"
docstr-coverage = "==2.3.2"
pydoctest = "==0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
