[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = [ "poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0" ]

[tool.poetry]
name = "vocab-tester"
version = "0.0.0"  # placeholder
description = "An application that tests Latin vocabulary and grammar."
authors = [ "rduo1009 <robertduong09alt@gmail.com>" ]
readme = "README.md"
packages = [ { include = "src" } ]
include = [ "nltk_data/**/*.zip" ]
dependencies.python = ">=3.12,<4.0"
dependencies.dill = "0.3.9"
dependencies.dunamai = "1.23.0"
dependencies.inflect = "7.4.0"
dependencies.lemminflect = "0.2.3"
dependencies.lz4 = "4.3.3"
dependencies.nltk = "3.9.1"
group.dev.dependencies.codetiming = "1.4.0"
group.dev.dependencies.cosmic-ray = "8.4.1"
group.dev.dependencies.coverage = "7.6.9"
group.dev.dependencies.deptry = "0.21.2"
group.dev.dependencies.doc8 = "1.1.2"
group.dev.dependencies.icecream = "2.1.3"
group.dev.dependencies.interrogate = "1.7.0"
group.dev.dependencies.monkeytype = "23.3.0"
group.dev.dependencies.mypy = { version = "1.14.1", extras = [ "faster-cache" ] }
group.dev.dependencies.pydoclint = "0.5.14"
group.dev.dependencies.pytest = "8.3.4"
group.dev.dependencies.pytest-cov = "6.0.0"
group.dev.dependencies.pytest-sugar = "1.0.0"
group.dev.dependencies.pytest-testmon = "2.1.1"
group.dev.dependencies.pytest-watch = "4.2.0"
group.dev.dependencies.pytest-xdist = "3.6.1"
group.dev.dependencies.rstfmt = "0.0.14"
group.dev.dependencies.ruff = "0.8.4"
group.types.dependencies.optype = "0.7.3"
group.types.dependencies.types-regex = "2024.11.6.20241108"

[tool.poetry-dynamic-versioning]
enable = true
