[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core" ]

[tool.poetry]
name = "vocab-tester"
version = "0.3.2-dev"
description = "An application that tests Latin vocabulary and grammar."
authors = [ "rduo1009 <robertduong09alt@gmail.com>" ]
readme = "README.md"
packages = [ { include = "python_src" } ]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
dill = "==0.3.9"
nltk = "==3.9.1"
lemminflect = "==0.2.3"
inflect = "==7.4.0"
lz4 = "==4.3.3"
aenum = "==3.1.15"

[tool.poetry.group.dev.dependencies]
icecream = "==2.1.3"
mypy = "==1.11.2"
ruff = "==0.6.8"
pytest = "==8.3.3"
monkeytype = "==23.3.0"
coverage = "==7.6.3"
pytest-cov = "==5.0.0"
pytest-sugar = "==1.0.0"
codetiming = "==1.4.0"
pytest-xdist = "==3.6.1"
docstr-coverage = "==2.3.2"
pydoctest = "==0.2.1"
pytest-testmon = "==2.1.1"
pytest-watch = "==4.2.0"

[tool.poetry.group.types.dependencies]
types-regex = "==2024.9.11.20240912"
