[tool.poetry]
name = "vocab-tester"
version = "0.1.0"
description = "An application that tests Latin vocabulary and grammar."
authors = ["rduo1009 <robertduong09alt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dill = "^0.3.8"
nltk = "^3.8.1"
lemminflect = "^0.2.3"
frozendict = "^2.4.4"

[tool.poetry.group.dev.dependencies]
icecream = "*"
mypy = "*"
ruff = "*"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false

[tool.ruff]
line-length = 79

[tool.mypy]
strict = true
warn_return_any = true
warn_unreachable = true
strict_equality = true
mypy_path = "mypy_stubs"
