line-length = 79
unsafe-fixes = true
extend-include = ["*.coco"]

[lint]
preview = true
exclude = ["*.coco", "*.py"]

[lint.pydocstyle]
convention = "numpy"

[format]
preview = true
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 72
exclude = ["*.py", "cache.coco"]
