from typing import List

from _typeshed import Incomplete

class Senna:
    def __init__(
        self, senna_path: str, operations: List[str], encoding: str = ...
    ) -> None: ...
    def executable(self, base_path: str) -> str: ...
    def tag(self, tokens: List[str]) -> Incomplete: ...
    def tag_sents(self, sentences: List[List[str]]) -> Incomplete: ...
