from _typeshed import Incomplete

from nltk.util import trigrams as trigrams

class TextCat:
    fingerprints: Incomplete
    last_distances: Incomplete
    def __init__(self) -> None: ...
    def remove_punctuation(self, text: Incomplete) -> Incomplete: ...
    def profile(self, text: Incomplete) -> Incomplete: ...
    def calc_dist(
        self, lang: Incomplete, trigram: Incomplete, text_profile: Incomplete
    ) -> Incomplete: ...
    def lang_dists(self, text: Incomplete) -> Incomplete: ...
    def guess_language(self, text: Incomplete) -> Incomplete: ...

def demo() -> None: ...
