from _typeshed import Incomplete

from nltk.draw.util import CanvasFrame as CanvasFrame
from nltk.draw.util import ShowText as ShowText
from nltk.parse import MaltParser as MaltParser
from nltk.sem.drt import DrsDrawer as DrsDrawer
from nltk.sem.drt import DrtVariableExpression as DrtVariableExpression
from nltk.sem.glue import DrtGlue as DrtGlue
from nltk.sem.logic import Variable as Variable
from nltk.tag import RegexpTagger as RegexpTagger
from nltk.util import in_idle as in_idle

class DrtGlueDemo:
    def __init__(self, examples: Incomplete) -> None: ...
    def destroy(self, *e: Incomplete) -> None: ...
    def prev(self, *e: Incomplete) -> None: ...
    def next(self, *e: Incomplete) -> None: ...
    def about(self, *e: Incomplete) -> None: ...
    def postscript(self, *e: Incomplete) -> None: ...
    def mainloop(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def resize(self, size: Incomplete | None = None) -> None: ...

class DrsWidget:
    bbox: Incomplete
    def __init__(
        self, canvas: Incomplete, drs: Incomplete, **attribs: Incomplete
    ) -> None: ...
    def draw(self) -> None: ...
    def clear(self) -> None: ...

def demo() -> None: ...
