from _typeshed import Incomplete

NE_CLASSES: Incomplete
short2long: Incomplete
long2short: Incomplete

def class_abbrev(type: Incomplete) -> Incomplete: ...
def descape_entity(m: Incomplete, defs: Incomplete = ...) -> Incomplete: ...
def list2sym(lst: Incomplete) -> Incomplete: ...
def tree2semi_rel(tree: Incomplete) -> Incomplete: ...
def semi_rel2reldict(
    pairs: Incomplete, window: int = 5, trace: bool = False
) -> Incomplete: ...
def extract_rels(
    subjclass: Incomplete,
    objclass: Incomplete,
    doc: Incomplete,
    corpus: str = "ace",
    pattern: Incomplete | None = None,
    window: int = 10,
) -> Incomplete: ...
def rtuple(
    reldict: Incomplete, lcon: bool = False, rcon: bool = False
) -> Incomplete: ...
def clause(reldict: Incomplete, relsym: Incomplete) -> Incomplete: ...
def in_demo(trace: int = 0, sql: bool = True) -> None: ...
def roles_demo(trace: int = 0) -> None: ...
def ieer_headlines() -> None: ...
def conllned(trace: int = 1) -> None: ...
def conllesp() -> None: ...
def ne_chunked() -> None: ...
