from _typeshed import Incomplete

from nltk.draw.util import (
    BoxWidget as BoxWidget,
)
from nltk.draw.util import (
    CanvasFrame as CanvasFrame,
)
from nltk.draw.util import (
    CanvasWidget as CanvasWidget,
)
from nltk.draw.util import (
    OvalWidget as OvalWidget,
)
from nltk.draw.util import (
    ParenWidget as ParenWidget,
)
from nltk.draw.util import (
    TextWidget as TextWidget,
)
from nltk.tree import Tree as Tree
from nltk.util import in_idle as in_idle

class TreeSegmentWidget(CanvasWidget):
    def __init__(
        self,
        canvas: Incomplete,
        label: Incomplete,
        subtrees: Incomplete,
        **attribs: Incomplete,
    ) -> None: ...
    def __setitem__(self, attr: Incomplete, value: Incomplete) -> None: ...
    def __getitem__(self, attr: Incomplete) -> Incomplete: ...
    def label(self) -> Incomplete: ...
    def subtrees(self) -> Incomplete: ...
    def set_label(self, label: Incomplete) -> None: ...
    def replace_child(
        self, oldchild: Incomplete, newchild: Incomplete
    ) -> None: ...
    def remove_child(self, child: Incomplete) -> None: ...
    def insert_child(self, index: Incomplete, child: Incomplete) -> None: ...

def tree_to_treesegment(
    canvas: Incomplete,
    t: Incomplete,
    make_node: Incomplete = ...,
    make_leaf: Incomplete = ...,
    **attribs: Incomplete,
) -> Incomplete: ...

class TreeWidget(CanvasWidget):
    def __init__(
        self,
        canvas: Incomplete,
        t: Incomplete,
        make_node: Incomplete = ...,
        make_leaf: Incomplete = ...,
        **attribs: Incomplete,
    ) -> None: ...
    def expanded_tree(self, *path_to_tree: Incomplete) -> Incomplete: ...
    def collapsed_tree(self, *path_to_tree: Incomplete) -> Incomplete: ...
    def bind_click_trees(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def bind_drag_trees(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def bind_click_leaves(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def bind_drag_leaves(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def bind_click_nodes(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def bind_drag_nodes(
        self, callback: Incomplete, button: int = 1
    ) -> None: ...
    def __setitem__(self, attr: Incomplete, value: Incomplete) -> None: ...
    def __getitem__(self, attr: Incomplete) -> Incomplete: ...
    def toggle_collapsed(self, treeseg: Incomplete) -> None: ...

class TreeView:
    def __init__(self, *trees: Incomplete) -> None: ...
    def resize(self, *e: Incomplete) -> None: ...
    def destroy(self, *e: Incomplete) -> None: ...
    def mainloop(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

def draw_trees(*trees: Incomplete) -> None: ...
def demo() -> Incomplete: ...
