# Auto-generated by stubgen

from _typeshed import Incomplete

from .KerasModel import KerasModel

class ModelInfl(KerasModel):
    def __init__(self) -> None: ...
    model: Incomplete
    def create(
        self,
        input_len: Incomplete,
        input_letters: Incomplete,
        output_classes: Incomplete,
    ) -> None: ...
    def train(
        self,
        xdata: Incomplete,
        ydata: Incomplete,
        batch_size: Incomplete,
        nepochs: Incomplete,
        **kwargs: Incomplete,
    ) -> None: ...
