import sys, os  # noqa: E401

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pytest
from grammatica.endings import Adjective


def test_repr():
    word = Adjective("laetus", "laeta", "laetum", declension="212", meaning="happy")
    assert word.__repr__() == "Adjective(laetus, laeta, laetum, None, 212, happy)"


def test_eq():
    word1 = Adjective("laetus", "laeta", "laetum", declension="212", meaning="happy")
    word2 = Adjective("laetus", "laeta", "laetum", declension="212", meaning="happy")
    assert word1 == word2


def test_lt():
    word1 = Adjective("aalaetus", "laeta", "laetum", declension="212", meaning="happy")
    word2 = Adjective("laetus", "laeta", "laetum", declension="212", meaning="happy")
    assert word1 < word2


def test_declension212():
    word = Adjective("laetus", "laeta", "laetum", declension="212", meaning="happy")
    assert word.get("positive", "masculine", "nominative", "singular") == "laetus"
    assert word.get("positive", "masculine", "vocative", "singular") == "laete"
    assert word.get("positive", "masculine", "accusative", "singular") == "laetum"
    assert word.get("positive", "masculine", "genitive", "singular") == "laeti"
    assert word.get("positive", "masculine", "dative", "singular") == "laeto"
    assert word.get("positive", "masculine", "ablative", "singular") == "laeto"
    assert word.get("positive", "masculine", "nominative", "plural") == "laeti"
    assert word.get("positive", "masculine", "vocative", "plural") == "laeti"
    assert word.get("positive", "masculine", "accusative", "plural") == "laetos"
    assert word.get("positive", "masculine", "genitive", "plural") == "laetorum"
    assert word.get("positive", "masculine", "dative", "plural") == "laetis"
    assert word.get("positive", "masculine", "ablative", "plural") == "laetis"

    assert word.get("positive", "feminine", "nominative", "singular") == "laeta"
    assert word.get("positive", "feminine", "vocative", "singular") == "laeta"
    assert word.get("positive", "feminine", "accusative", "singular") == "laetam"
    assert word.get("positive", "feminine", "genitive", "singular") == "laetae"
    assert word.get("positive", "feminine", "dative", "singular") == "laetae"
    assert word.get("positive", "feminine", "ablative", "singular") == "laeta"
    assert word.get("positive", "feminine", "nominative", "plural") == "laetae"
    assert word.get("positive", "feminine", "vocative", "plural") == "laetae"
    assert word.get("positive", "feminine", "accusative", "plural") == "laetas"
    assert word.get("positive", "feminine", "genitive", "plural") == "laetarum"
    assert word.get("positive", "feminine", "dative", "plural") == "laetis"
    assert word.get("positive", "feminine", "ablative", "plural") == "laetis"

    assert word.get("positive", "neuter", "nominative", "singular") == "laetum"
    assert word.get("positive", "neuter", "vocative", "singular") == "laetum"
    assert word.get("positive", "neuter", "accusative", "singular") == "laetum"
    assert word.get("positive", "neuter", "genitive", "singular") == "laeti"
    assert word.get("positive", "neuter", "dative", "singular") == "laeto"
    assert word.get("positive", "neuter", "ablative", "singular") == "laeto"
    assert word.get("positive", "neuter", "nominative", "plural") == "laeta"
    assert word.get("positive", "neuter", "vocative", "plural") == "laeta"
    assert word.get("positive", "neuter", "accusative", "plural") == "laeta"
    assert word.get("positive", "neuter", "genitive", "plural") == "laetorum"
    assert word.get("positive", "neuter", "dative", "plural") == "laetis"
    assert word.get("positive", "neuter", "ablative", "plural") == "laetis"

    assert word.get("comparative", "masculine", "nominative", "singular") == "laetior"
    assert word.get("comparative", "masculine", "vocative", "singular") == "laetior"
    assert word.get("comparative", "masculine", "accusative", "singular") == "laetiorem"
    assert word.get("comparative", "masculine", "genitive", "singular") == "laetioris"
    assert word.get("comparative", "masculine", "dative", "singular") == "laetiori"
    assert word.get("comparative", "masculine", "ablative", "singular") == "laetiore"
    assert word.get("comparative", "masculine", "nominative", "plural") == "laetiores"
    assert word.get("comparative", "masculine", "vocative", "plural") == "laetiores"
    assert word.get("comparative", "masculine", "accusative", "plural") == "laetiores"
    assert word.get("comparative", "masculine", "genitive", "plural") == "laetiorum"
    assert word.get("comparative", "masculine", "dative", "plural") == "laetioribus"
    assert word.get("comparative", "masculine", "ablative", "plural") == "laetioribus"

    assert word.get("comparative", "feminine", "nominative", "singular") == "laetior"
    assert word.get("comparative", "feminine", "vocative", "singular") == "laetior"
    assert word.get("comparative", "feminine", "accusative", "singular") == "laetiorem"
    assert word.get("comparative", "feminine", "genitive", "singular") == "laetioris"
    assert word.get("comparative", "feminine", "dative", "singular") == "laetiori"
    assert word.get("comparative", "feminine", "ablative", "singular") == "laetiore"
    assert word.get("comparative", "feminine", "nominative", "plural") == "laetiores"
    assert word.get("comparative", "feminine", "vocative", "plural") == "laetiores"
    assert word.get("comparative", "feminine", "accusative", "plural") == "laetiores"
    assert word.get("comparative", "feminine", "genitive", "plural") == "laetiorum"
    assert word.get("comparative", "feminine", "dative", "plural") == "laetioribus"
    assert word.get("comparative", "feminine", "ablative", "plural") == "laetioribus"

    assert word.get("comparative", "neuter", "nominative", "singular") == "laetius"
    assert word.get("comparative", "neuter", "vocative", "singular") == "laetius"
    assert word.get("comparative", "neuter", "accusative", "singular") == "laetius"
    assert word.get("comparative", "neuter", "genitive", "singular") == "laetioris"
    assert word.get("comparative", "neuter", "dative", "singular") == "laetiori"
    assert word.get("comparative", "neuter", "ablative", "singular") == "laetiore"
    assert word.get("comparative", "neuter", "nominative", "plural") == "laetiora"
    assert word.get("comparative", "neuter", "vocative", "plural") == "laetiora"
    assert word.get("comparative", "neuter", "accusative", "plural") == "laetiora"
    assert word.get("comparative", "neuter", "genitive", "plural") == "laetiorum"
    assert word.get("comparative", "neuter", "dative", "plural") == "laetioribus"
    assert word.get("comparative", "neuter", "ablative", "plural") == "laetioribus"

    assert (
        word.get("superlative", "masculine", "nominative", "singular") == "laetissimus"
    )
    assert word.get("superlative", "masculine", "vocative", "singular") == "laetissime"
    assert (
        word.get("superlative", "masculine", "accusative", "singular") == "laetissimum"
    )
    assert word.get("superlative", "masculine", "genitive", "singular") == "laetissimi"
    assert word.get("superlative", "masculine", "dative", "singular") == "laetissimo"
    assert word.get("superlative", "masculine", "ablative", "singular") == "laetissimo"
    assert word.get("superlative", "masculine", "nominative", "plural") == "laetissimi"
    assert word.get("superlative", "masculine", "vocative", "plural") == "laetissimi"
    assert word.get("superlative", "masculine", "accusative", "plural") == "laetissimos"
    assert word.get("superlative", "masculine", "genitive", "plural") == "laetissimorum"
    assert word.get("superlative", "masculine", "dative", "plural") == "laetissimis"
    assert word.get("superlative", "masculine", "ablative", "plural") == "laetissimis"

    assert word.get("superlative", "feminine", "nominative", "singular") == "laetissima"
    assert word.get("superlative", "feminine", "vocative", "singular") == "laetissima"
    assert (
        word.get("superlative", "feminine", "accusative", "singular") == "laetissimam"
    )
    assert word.get("superlative", "feminine", "genitive", "singular") == "laetissimae"
    assert word.get("superlative", "feminine", "dative", "singular") == "laetissimae"
    assert word.get("superlative", "feminine", "ablative", "singular") == "laetissima"
    assert word.get("superlative", "feminine", "nominative", "plural") == "laetissimae"
    assert word.get("superlative", "feminine", "vocative", "plural") == "laetissimae"
    assert word.get("superlative", "feminine", "accusative", "plural") == "laetissimas"
    assert word.get("superlative", "feminine", "genitive", "plural") == "laetissimarum"
    assert word.get("superlative", "feminine", "dative", "plural") == "laetissimis"
    assert word.get("superlative", "feminine", "ablative", "plural") == "laetissimis"

    assert word.get("superlative", "neuter", "nominative", "singular") == "laetissimum"
    assert word.get("superlative", "neuter", "vocative", "singular") == "laetissimum"
    assert word.get("superlative", "neuter", "accusative", "singular") == "laetissimum"
    assert word.get("superlative", "neuter", "genitive", "singular") == "laetissimi"
    assert word.get("superlative", "neuter", "dative", "singular") == "laetissimo"
    assert word.get("superlative", "neuter", "ablative", "singular") == "laetissimo"
    assert word.get("superlative", "neuter", "nominative", "plural") == "laetissima"
    assert word.get("superlative", "neuter", "vocative", "plural") == "laetissima"
    assert word.get("superlative", "neuter", "accusative", "plural") == "laetissima"
    assert word.get("superlative", "neuter", "genitive", "plural") == "laetissimorum"
    assert word.get("superlative", "neuter", "dative", "plural") == "laetissimis"
    assert word.get("superlative", "neuter", "ablative", "plural") == "laetissimis"


def test_declension212_irregular():
    word = Adjective("bonus", "bona", "bonum", declension="212", meaning="happy")
    assert word.get("positive", "masculine", "nominative", "singular") == "bonus"
    assert word.get("positive", "masculine", "vocative", "singular") == "bone"
    assert word.get("positive", "masculine", "accusative", "singular") == "bonum"
    assert word.get("positive", "masculine", "genitive", "singular") == "boni"
    assert word.get("positive", "masculine", "dative", "singular") == "bono"
    assert word.get("positive", "masculine", "ablative", "singular") == "bono"
    assert word.get("positive", "masculine", "nominative", "plural") == "boni"
    assert word.get("positive", "masculine", "vocative", "plural") == "boni"
    assert word.get("positive", "masculine", "accusative", "plural") == "bonos"
    assert word.get("positive", "masculine", "genitive", "plural") == "bonorum"
    assert word.get("positive", "masculine", "dative", "plural") == "bonis"
    assert word.get("positive", "masculine", "ablative", "plural") == "bonis"

    assert word.get("positive", "feminine", "nominative", "singular") == "bona"
    assert word.get("positive", "feminine", "vocative", "singular") == "bona"
    assert word.get("positive", "feminine", "accusative", "singular") == "bonam"
    assert word.get("positive", "feminine", "genitive", "singular") == "bonae"
    assert word.get("positive", "feminine", "dative", "singular") == "bonae"
    assert word.get("positive", "feminine", "ablative", "singular") == "bona"
    assert word.get("positive", "feminine", "nominative", "plural") == "bonae"
    assert word.get("positive", "feminine", "vocative", "plural") == "bonae"
    assert word.get("positive", "feminine", "accusative", "plural") == "bonas"
    assert word.get("positive", "feminine", "genitive", "plural") == "bonarum"
    assert word.get("positive", "feminine", "dative", "plural") == "bonis"
    assert word.get("positive", "feminine", "ablative", "plural") == "bonis"

    assert word.get("positive", "neuter", "nominative", "singular") == "bonum"
    assert word.get("positive", "neuter", "vocative", "singular") == "bonum"
    assert word.get("positive", "neuter", "accusative", "singular") == "bonum"
    assert word.get("positive", "neuter", "genitive", "singular") == "boni"
    assert word.get("positive", "neuter", "dative", "singular") == "bono"
    assert word.get("positive", "neuter", "ablative", "singular") == "bono"
    assert word.get("positive", "neuter", "nominative", "plural") == "bona"
    assert word.get("positive", "neuter", "vocative", "plural") == "bona"
    assert word.get("positive", "neuter", "accusative", "plural") == "bona"
    assert word.get("positive", "neuter", "genitive", "plural") == "bonorum"
    assert word.get("positive", "neuter", "dative", "plural") == "bonis"
    assert word.get("positive", "neuter", "ablative", "plural") == "bonis"

    assert word.get("comparative", "masculine", "nominative", "singular") == "melior"
    assert word.get("comparative", "masculine", "vocative", "singular") == "melior"
    assert word.get("comparative", "masculine", "accusative", "singular") == "meliorem"
    assert word.get("comparative", "masculine", "genitive", "singular") == "melioris"
    assert word.get("comparative", "masculine", "dative", "singular") == "meliori"
    assert word.get("comparative", "masculine", "ablative", "singular") == "meliore"
    assert word.get("comparative", "masculine", "nominative", "plural") == "meliores"
    assert word.get("comparative", "masculine", "vocative", "plural") == "meliores"
    assert word.get("comparative", "masculine", "accusative", "plural") == "meliores"
    assert word.get("comparative", "masculine", "genitive", "plural") == "meliorum"
    assert word.get("comparative", "masculine", "dative", "plural") == "melioribus"
    assert word.get("comparative", "masculine", "ablative", "plural") == "melioribus"

    assert word.get("comparative", "feminine", "nominative", "singular") == "melior"
    assert word.get("comparative", "feminine", "vocative", "singular") == "melior"
    assert word.get("comparative", "feminine", "accusative", "singular") == "meliorem"
    assert word.get("comparative", "feminine", "genitive", "singular") == "melioris"
    assert word.get("comparative", "feminine", "dative", "singular") == "meliori"
    assert word.get("comparative", "feminine", "ablative", "singular") == "meliore"
    assert word.get("comparative", "feminine", "nominative", "plural") == "meliores"
    assert word.get("comparative", "feminine", "vocative", "plural") == "meliores"
    assert word.get("comparative", "feminine", "accusative", "plural") == "meliores"
    assert word.get("comparative", "feminine", "genitive", "plural") == "meliorum"
    assert word.get("comparative", "feminine", "dative", "plural") == "melioribus"
    assert word.get("comparative", "feminine", "ablative", "plural") == "melioribus"

    assert word.get("comparative", "neuter", "nominative", "singular") == "melius"
    assert word.get("comparative", "neuter", "vocative", "singular") == "melius"
    assert word.get("comparative", "neuter", "accusative", "singular") == "melius"
    assert word.get("comparative", "neuter", "genitive", "singular") == "melioris"
    assert word.get("comparative", "neuter", "dative", "singular") == "meliori"
    assert word.get("comparative", "neuter", "ablative", "singular") == "meliore"
    assert word.get("comparative", "neuter", "nominative", "plural") == "meliora"
    assert word.get("comparative", "neuter", "vocative", "plural") == "meliora"
    assert word.get("comparative", "neuter", "accusative", "plural") == "meliora"
    assert word.get("comparative", "neuter", "genitive", "plural") == "meliorum"
    assert word.get("comparative", "neuter", "dative", "plural") == "melioribus"
    assert word.get("comparative", "neuter", "ablative", "plural") == "melioribus"

    assert word.get("superlative", "masculine", "nominative", "singular") == "optimus"
    assert word.get("superlative", "masculine", "vocative", "singular") == "optime"
    assert word.get("superlative", "masculine", "accusative", "singular") == "optimum"
    assert word.get("superlative", "masculine", "genitive", "singular") == "optimi"
    assert word.get("superlative", "masculine", "dative", "singular") == "optimo"
    assert word.get("superlative", "masculine", "ablative", "singular") == "optimo"
    assert word.get("superlative", "masculine", "nominative", "plural") == "optimi"
    assert word.get("superlative", "masculine", "vocative", "plural") == "optimi"
    assert word.get("superlative", "masculine", "accusative", "plural") == "optimos"
    assert word.get("superlative", "masculine", "genitive", "plural") == "optimorum"
    assert word.get("superlative", "masculine", "dative", "plural") == "optimis"
    assert word.get("superlative", "masculine", "ablative", "plural") == "optimis"

    assert word.get("superlative", "feminine", "nominative", "singular") == "optima"
    assert word.get("superlative", "feminine", "vocative", "singular") == "optima"
    assert word.get("superlative", "feminine", "accusative", "singular") == "optimam"
    assert word.get("superlative", "feminine", "genitive", "singular") == "optimae"
    assert word.get("superlative", "feminine", "dative", "singular") == "optimae"
    assert word.get("superlative", "feminine", "ablative", "singular") == "optima"
    assert word.get("superlative", "feminine", "nominative", "plural") == "optimae"
    assert word.get("superlative", "feminine", "vocative", "plural") == "optimae"
    assert word.get("superlative", "feminine", "accusative", "plural") == "optimas"
    assert word.get("superlative", "feminine", "genitive", "plural") == "optimarum"
    assert word.get("superlative", "feminine", "dative", "plural") == "optimis"
    assert word.get("superlative", "feminine", "ablative", "plural") == "optimis"

    assert word.get("superlative", "neuter", "nominative", "singular") == "optimum"
    assert word.get("superlative", "neuter", "vocative", "singular") == "optimum"
    assert word.get("superlative", "neuter", "accusative", "singular") == "optimum"
    assert word.get("superlative", "neuter", "genitive", "singular") == "optimi"
    assert word.get("superlative", "neuter", "dative", "singular") == "optimo"
    assert word.get("superlative", "neuter", "ablative", "singular") == "optimo"
    assert word.get("superlative", "neuter", "nominative", "plural") == "optima"
    assert word.get("superlative", "neuter", "vocative", "plural") == "optima"
    assert word.get("superlative", "neuter", "accusative", "plural") == "optima"
    assert word.get("superlative", "neuter", "genitive", "plural") == "optimorum"
    assert word.get("superlative", "neuter", "dative", "plural") == "optimis"
    assert word.get("superlative", "neuter", "ablative", "plural") == "optimis"


def test_declension3_1():
    word = Adjective("egens", "egentis", termination=1, declension="3", meaning="poor")
    assert word.get("positive", "masculine", "nominative", "singular") == "egens"
    assert word.get("positive", "masculine", "vocative", "singular") == "egens"
    assert word.get("positive", "masculine", "accusative", "singular") == "egentem"
    assert word.get("positive", "masculine", "genitive", "singular") == "egentis"
    assert word.get("positive", "masculine", "dative", "singular") == "egenti"
    assert word.get("positive", "masculine", "ablative", "singular") == "egenti"
    assert word.get("positive", "masculine", "nominative", "plural") == "egentes"
    assert word.get("positive", "masculine", "vocative", "plural") == "egentes"
    assert word.get("positive", "masculine", "accusative", "plural") == "egentes"
    assert word.get("positive", "masculine", "genitive", "plural") == "egentium"
    assert word.get("positive", "masculine", "dative", "plural") == "egentibus"
    assert word.get("positive", "masculine", "ablative", "plural") == "egentibus"

    assert word.get("positive", "feminine", "nominative", "singular") == "egens"
    assert word.get("positive", "feminine", "vocative", "singular") == "egens"
    assert word.get("positive", "feminine", "accusative", "singular") == "egentem"
    assert word.get("positive", "feminine", "genitive", "singular") == "egentis"
    assert word.get("positive", "feminine", "dative", "singular") == "egenti"
    assert word.get("positive", "feminine", "ablative", "singular") == "egenti"
    assert word.get("positive", "feminine", "nominative", "plural") == "egentes"
    assert word.get("positive", "feminine", "vocative", "plural") == "egentes"
    assert word.get("positive", "feminine", "accusative", "plural") == "egentes"
    assert word.get("positive", "feminine", "genitive", "plural") == "egentium"
    assert word.get("positive", "feminine", "dative", "plural") == "egentibus"
    assert word.get("positive", "feminine", "ablative", "plural") == "egentibus"

    assert word.get("positive", "neuter", "nominative", "singular") == "egens"
    assert word.get("positive", "neuter", "vocative", "singular") == "egens"
    assert word.get("positive", "neuter", "accusative", "singular") == "egens"
    assert word.get("positive", "neuter", "genitive", "singular") == "egentis"
    assert word.get("positive", "neuter", "dative", "singular") == "egenti"
    assert word.get("positive", "neuter", "ablative", "singular") == "egenti"
    assert word.get("positive", "neuter", "nominative", "plural") == "egentia"
    assert word.get("positive", "neuter", "vocative", "plural") == "egentia"
    assert word.get("positive", "neuter", "accusative", "plural") == "egentia"
    assert word.get("positive", "neuter", "genitive", "plural") == "egentium"
    assert word.get("positive", "neuter", "dative", "plural") == "egentibus"
    assert word.get("positive", "neuter", "ablative", "plural") == "egentibus"

    assert word.get("comparative", "masculine", "nominative", "singular") == "egentior"
    assert word.get("comparative", "masculine", "vocative", "singular") == "egentior"
    assert (
        word.get("comparative", "masculine", "accusative", "singular") == "egentiorem"
    )
    assert word.get("comparative", "masculine", "genitive", "singular") == "egentioris"
    assert word.get("comparative", "masculine", "dative", "singular") == "egentiori"
    assert word.get("comparative", "masculine", "ablative", "singular") == "egentiore"
    assert word.get("comparative", "masculine", "nominative", "plural") == "egentiores"
    assert word.get("comparative", "masculine", "vocative", "plural") == "egentiores"
    assert word.get("comparative", "masculine", "accusative", "plural") == "egentiores"
    assert word.get("comparative", "masculine", "genitive", "plural") == "egentiorum"
    assert word.get("comparative", "masculine", "dative", "plural") == "egentioribus"
    assert word.get("comparative", "masculine", "ablative", "plural") == "egentioribus"

    assert word.get("comparative", "feminine", "nominative", "singular") == "egentior"
    assert word.get("comparative", "feminine", "vocative", "singular") == "egentior"
    assert word.get("comparative", "feminine", "accusative", "singular") == "egentiorem"
    assert word.get("comparative", "feminine", "genitive", "singular") == "egentioris"
    assert word.get("comparative", "feminine", "dative", "singular") == "egentiori"
    assert word.get("comparative", "feminine", "ablative", "singular") == "egentiore"
    assert word.get("comparative", "feminine", "nominative", "plural") == "egentiores"
    assert word.get("comparative", "feminine", "vocative", "plural") == "egentiores"
    assert word.get("comparative", "feminine", "accusative", "plural") == "egentiores"
    assert word.get("comparative", "feminine", "genitive", "plural") == "egentiorum"
    assert word.get("comparative", "feminine", "dative", "plural") == "egentioribus"
    assert word.get("comparative", "feminine", "ablative", "plural") == "egentioribus"

    assert word.get("comparative", "neuter", "nominative", "singular") == "egentius"
    assert word.get("comparative", "neuter", "vocative", "singular") == "egentius"
    assert word.get("comparative", "neuter", "accusative", "singular") == "egentius"
    assert word.get("comparative", "neuter", "genitive", "singular") == "egentioris"
    assert word.get("comparative", "neuter", "dative", "singular") == "egentiori"
    assert word.get("comparative", "neuter", "ablative", "singular") == "egentiore"
    assert word.get("comparative", "neuter", "nominative", "plural") == "egentiora"
    assert word.get("comparative", "neuter", "vocative", "plural") == "egentiora"
    assert word.get("comparative", "neuter", "accusative", "plural") == "egentiora"
    assert word.get("comparative", "neuter", "genitive", "plural") == "egentiorum"
    assert word.get("comparative", "neuter", "dative", "plural") == "egentioribus"
    assert word.get("comparative", "neuter", "ablative", "plural") == "egentioribus"

    assert (
        word.get("superlative", "masculine", "nominative", "singular") == "egentissimus"
    )
    assert word.get("superlative", "masculine", "vocative", "singular") == "egentissime"
    assert (
        word.get("superlative", "masculine", "accusative", "singular") == "egentissimum"
    )
    assert word.get("superlative", "masculine", "genitive", "singular") == "egentissimi"
    assert word.get("superlative", "masculine", "dative", "singular") == "egentissimo"
    assert word.get("superlative", "masculine", "ablative", "singular") == "egentissimo"
    assert word.get("superlative", "masculine", "nominative", "plural") == "egentissimi"
    assert word.get("superlative", "masculine", "vocative", "plural") == "egentissimi"
    assert (
        word.get("superlative", "masculine", "accusative", "plural") == "egentissimos"
    )
    assert (
        word.get("superlative", "masculine", "genitive", "plural") == "egentissimorum"
    )
    assert word.get("superlative", "masculine", "dative", "plural") == "egentissimis"
    assert word.get("superlative", "masculine", "ablative", "plural") == "egentissimis"

    assert (
        word.get("superlative", "feminine", "nominative", "singular") == "egentissima"
    )
    assert word.get("superlative", "feminine", "vocative", "singular") == "egentissima"
    assert (
        word.get("superlative", "feminine", "accusative", "singular") == "egentissimam"
    )
    assert word.get("superlative", "feminine", "genitive", "singular") == "egentissimae"
    assert word.get("superlative", "feminine", "dative", "singular") == "egentissimae"
    assert word.get("superlative", "feminine", "ablative", "singular") == "egentissima"
    assert word.get("superlative", "feminine", "nominative", "plural") == "egentissimae"
    assert word.get("superlative", "feminine", "vocative", "plural") == "egentissimae"
    assert word.get("superlative", "feminine", "accusative", "plural") == "egentissimas"
    assert word.get("superlative", "feminine", "genitive", "plural") == "egentissimarum"
    assert word.get("superlative", "feminine", "dative", "plural") == "egentissimis"
    assert word.get("superlative", "feminine", "ablative", "plural") == "egentissimis"

    assert word.get("superlative", "neuter", "nominative", "singular") == "egentissimum"
    assert word.get("superlative", "neuter", "vocative", "singular") == "egentissimum"
    assert word.get("superlative", "neuter", "accusative", "singular") == "egentissimum"
    assert word.get("superlative", "neuter", "genitive", "singular") == "egentissimi"
    assert word.get("superlative", "neuter", "dative", "singular") == "egentissimo"
    assert word.get("superlative", "neuter", "ablative", "singular") == "egentissimo"
    assert word.get("superlative", "neuter", "nominative", "plural") == "egentissima"
    assert word.get("superlative", "neuter", "vocative", "plural") == "egentissima"
    assert word.get("superlative", "neuter", "accusative", "plural") == "egentissima"
    assert word.get("superlative", "neuter", "genitive", "plural") == "egentissimorum"
    assert word.get("superlative", "neuter", "dative", "plural") == "egentissimis"
    assert word.get("superlative", "neuter", "ablative", "plural") == "egentissimis"


def test_declension3_2():
    word = Adjective("facilis", "facile", termination=2, declension="3", meaning="easy")
    assert word.get("positive", "masculine", "nominative", "singular") == "facilis"
    assert word.get("positive", "masculine", "vocative", "singular") == "facilis"
    assert word.get("positive", "masculine", "accusative", "singular") == "facilem"
    assert word.get("positive", "masculine", "genitive", "singular") == "facilis"
    assert word.get("positive", "masculine", "dative", "singular") == "facili"
    assert word.get("positive", "masculine", "ablative", "singular") == "facili"
    assert word.get("positive", "masculine", "nominative", "plural") == "faciles"
    assert word.get("positive", "masculine", "vocative", "plural") == "faciles"
    assert word.get("positive", "masculine", "accusative", "plural") == "faciles"
    assert word.get("positive", "masculine", "genitive", "plural") == "facilium"
    assert word.get("positive", "masculine", "dative", "plural") == "facilibus"
    assert word.get("positive", "masculine", "ablative", "plural") == "facilibus"

    assert word.get("positive", "feminine", "nominative", "singular") == "facilis"
    assert word.get("positive", "feminine", "vocative", "singular") == "facilis"
    assert word.get("positive", "feminine", "accusative", "singular") == "facilem"
    assert word.get("positive", "feminine", "genitive", "singular") == "facilis"
    assert word.get("positive", "feminine", "dative", "singular") == "facili"
    assert word.get("positive", "feminine", "ablative", "singular") == "facili"
    assert word.get("positive", "feminine", "nominative", "plural") == "faciles"
    assert word.get("positive", "feminine", "vocative", "plural") == "faciles"
    assert word.get("positive", "feminine", "accusative", "plural") == "faciles"
    assert word.get("positive", "feminine", "genitive", "plural") == "facilium"
    assert word.get("positive", "feminine", "dative", "plural") == "facilibus"
    assert word.get("positive", "feminine", "ablative", "plural") == "facilibus"

    assert word.get("positive", "neuter", "nominative", "singular") == "facile"
    assert word.get("positive", "neuter", "vocative", "singular") == "facile"
    assert word.get("positive", "neuter", "accusative", "singular") == "facile"
    assert word.get("positive", "neuter", "genitive", "singular") == "facilis"
    assert word.get("positive", "neuter", "dative", "singular") == "facili"
    assert word.get("positive", "neuter", "ablative", "singular") == "facili"
    assert word.get("positive", "neuter", "nominative", "plural") == "facilia"
    assert word.get("positive", "neuter", "vocative", "plural") == "facilia"
    assert word.get("positive", "neuter", "accusative", "plural") == "facilia"
    assert word.get("positive", "neuter", "genitive", "plural") == "facilium"
    assert word.get("positive", "neuter", "dative", "plural") == "facilibus"
    assert word.get("positive", "neuter", "ablative", "plural") == "facilibus"

    assert word.get("comparative", "masculine", "nominative", "singular") == "facilior"
    assert word.get("comparative", "masculine", "vocative", "singular") == "facilior"
    assert (
        word.get("comparative", "masculine", "accusative", "singular") == "faciliorem"
    )
    assert word.get("comparative", "masculine", "genitive", "singular") == "facilioris"
    assert word.get("comparative", "masculine", "dative", "singular") == "faciliori"
    assert word.get("comparative", "masculine", "ablative", "singular") == "faciliore"
    assert word.get("comparative", "masculine", "nominative", "plural") == "faciliores"
    assert word.get("comparative", "masculine", "vocative", "plural") == "faciliores"
    assert word.get("comparative", "masculine", "accusative", "plural") == "faciliores"
    assert word.get("comparative", "masculine", "genitive", "plural") == "faciliorum"
    assert word.get("comparative", "masculine", "dative", "plural") == "facilioribus"
    assert word.get("comparative", "masculine", "ablative", "plural") == "facilioribus"

    assert word.get("comparative", "feminine", "nominative", "singular") == "facilior"
    assert word.get("comparative", "feminine", "vocative", "singular") == "facilior"
    assert word.get("comparative", "feminine", "accusative", "singular") == "faciliorem"
    assert word.get("comparative", "feminine", "genitive", "singular") == "facilioris"
    assert word.get("comparative", "feminine", "dative", "singular") == "faciliori"
    assert word.get("comparative", "feminine", "ablative", "singular") == "faciliore"
    assert word.get("comparative", "feminine", "nominative", "plural") == "faciliores"
    assert word.get("comparative", "feminine", "vocative", "plural") == "faciliores"
    assert word.get("comparative", "feminine", "accusative", "plural") == "faciliores"
    assert word.get("comparative", "feminine", "genitive", "plural") == "faciliorum"
    assert word.get("comparative", "feminine", "dative", "plural") == "facilioribus"
    assert word.get("comparative", "feminine", "ablative", "plural") == "facilioribus"

    assert word.get("comparative", "neuter", "nominative", "singular") == "facilius"
    assert word.get("comparative", "neuter", "vocative", "singular") == "facilius"
    assert word.get("comparative", "neuter", "accusative", "singular") == "facilius"
    assert word.get("comparative", "neuter", "genitive", "singular") == "facilioris"
    assert word.get("comparative", "neuter", "dative", "singular") == "faciliori"
    assert word.get("comparative", "neuter", "ablative", "singular") == "faciliore"
    assert word.get("comparative", "neuter", "nominative", "plural") == "faciliora"
    assert word.get("comparative", "neuter", "vocative", "plural") == "faciliora"
    assert word.get("comparative", "neuter", "accusative", "plural") == "faciliora"
    assert word.get("comparative", "neuter", "genitive", "plural") == "faciliorum"
    assert word.get("comparative", "neuter", "dative", "plural") == "facilioribus"
    assert word.get("comparative", "neuter", "ablative", "plural") == "facilioribus"

    assert (
        word.get("superlative", "masculine", "nominative", "singular") == "facillimus"
    )
    assert word.get("superlative", "masculine", "vocative", "singular") == "facillime"
    assert (
        word.get("superlative", "masculine", "accusative", "singular") == "facillimum"
    )
    assert word.get("superlative", "masculine", "genitive", "singular") == "facillimi"
    assert word.get("superlative", "masculine", "dative", "singular") == "facillimo"
    assert word.get("superlative", "masculine", "ablative", "singular") == "facillimo"
    assert word.get("superlative", "masculine", "nominative", "plural") == "facillimi"
    assert word.get("superlative", "masculine", "vocative", "plural") == "facillimi"
    assert word.get("superlative", "masculine", "accusative", "plural") == "facillimos"
    assert word.get("superlative", "masculine", "genitive", "plural") == "facillimorum"
    assert word.get("superlative", "masculine", "dative", "plural") == "facillimis"
    assert word.get("superlative", "masculine", "ablative", "plural") == "facillimis"

    assert word.get("superlative", "feminine", "nominative", "singular") == "facillima"
    assert word.get("superlative", "feminine", "vocative", "singular") == "facillima"
    assert word.get("superlative", "feminine", "accusative", "singular") == "facillimam"
    assert word.get("superlative", "feminine", "genitive", "singular") == "facillimae"
    assert word.get("superlative", "feminine", "dative", "singular") == "facillimae"
    assert word.get("superlative", "feminine", "ablative", "singular") == "facillima"
    assert word.get("superlative", "feminine", "nominative", "plural") == "facillimae"
    assert word.get("superlative", "feminine", "vocative", "plural") == "facillimae"
    assert word.get("superlative", "feminine", "accusative", "plural") == "facillimas"
    assert word.get("superlative", "feminine", "genitive", "plural") == "facillimarum"
    assert word.get("superlative", "feminine", "dative", "plural") == "facillimis"
    assert word.get("superlative", "feminine", "ablative", "plural") == "facillimis"

    assert word.get("superlative", "neuter", "nominative", "singular") == "facillimum"
    assert word.get("superlative", "neuter", "vocative", "singular") == "facillimum"
    assert word.get("superlative", "neuter", "accusative", "singular") == "facillimum"
    assert word.get("superlative", "neuter", "genitive", "singular") == "facillimi"
    assert word.get("superlative", "neuter", "dative", "singular") == "facillimo"
    assert word.get("superlative", "neuter", "ablative", "singular") == "facillimo"
    assert word.get("superlative", "neuter", "nominative", "plural") == "facillima"
    assert word.get("superlative", "neuter", "vocative", "plural") == "facillima"
    assert word.get("superlative", "neuter", "accusative", "plural") == "facillima"
    assert word.get("superlative", "neuter", "genitive", "plural") == "facillimorum"
    assert word.get("superlative", "neuter", "dative", "plural") == "facillimis"
    assert word.get("superlative", "neuter", "ablative", "plural") == "facillimis"


def test_declension3_3():
    word = Adjective(
        "celer", "celeris", "celere", termination=3, declension="3", meaning="quick"
    )
    assert word.get("positive", "masculine", "nominative", "singular") == "celer"
    assert word.get("positive", "masculine", "vocative", "singular") == "celer"
    assert word.get("positive", "masculine", "accusative", "singular") == "celerem"
    assert word.get("positive", "masculine", "genitive", "singular") == "celeris"
    assert word.get("positive", "masculine", "dative", "singular") == "celeri"
    assert word.get("positive", "masculine", "ablative", "singular") == "celeri"
    assert word.get("positive", "masculine", "nominative", "plural") == "celeres"
    assert word.get("positive", "masculine", "vocative", "plural") == "celeres"
    assert word.get("positive", "masculine", "accusative", "plural") == "celeres"
    assert word.get("positive", "masculine", "genitive", "plural") == "celerium"
    assert word.get("positive", "masculine", "dative", "plural") == "celeribus"
    assert word.get("positive", "masculine", "ablative", "plural") == "celeribus"

    assert word.get("positive", "feminine", "nominative", "singular") == "celeris"
    assert word.get("positive", "feminine", "vocative", "singular") == "celeris"
    assert word.get("positive", "feminine", "accusative", "singular") == "celerem"
    assert word.get("positive", "feminine", "genitive", "singular") == "celeris"
    assert word.get("positive", "feminine", "dative", "singular") == "celeri"
    assert word.get("positive", "feminine", "ablative", "singular") == "celeri"
    assert word.get("positive", "feminine", "nominative", "plural") == "celeres"
    assert word.get("positive", "feminine", "vocative", "plural") == "celeres"
    assert word.get("positive", "feminine", "accusative", "plural") == "celeres"
    assert word.get("positive", "feminine", "genitive", "plural") == "celerium"
    assert word.get("positive", "feminine", "dative", "plural") == "celeribus"
    assert word.get("positive", "feminine", "ablative", "plural") == "celeribus"

    assert word.get("positive", "neuter", "nominative", "singular") == "celere"
    assert word.get("positive", "neuter", "vocative", "singular") == "celere"
    assert word.get("positive", "neuter", "accusative", "singular") == "celere"
    assert word.get("positive", "neuter", "genitive", "singular") == "celeris"
    assert word.get("positive", "neuter", "dative", "singular") == "celeri"
    assert word.get("positive", "neuter", "ablative", "singular") == "celeri"
    assert word.get("positive", "neuter", "nominative", "plural") == "celeria"
    assert word.get("positive", "neuter", "vocative", "plural") == "celeria"
    assert word.get("positive", "neuter", "accusative", "plural") == "celeria"
    assert word.get("positive", "neuter", "genitive", "plural") == "celerium"
    assert word.get("positive", "neuter", "dative", "plural") == "celeribus"
    assert word.get("positive", "neuter", "ablative", "plural") == "celeribus"

    assert word.get("comparative", "masculine", "nominative", "singular") == "celerior"
    assert word.get("comparative", "masculine", "vocative", "singular") == "celerior"
    assert (
        word.get("comparative", "masculine", "accusative", "singular") == "celeriorem"
    )
    assert word.get("comparative", "masculine", "genitive", "singular") == "celerioris"
    assert word.get("comparative", "masculine", "dative", "singular") == "celeriori"
    assert word.get("comparative", "masculine", "ablative", "singular") == "celeriore"
    assert word.get("comparative", "masculine", "nominative", "plural") == "celeriores"
    assert word.get("comparative", "masculine", "vocative", "plural") == "celeriores"
    assert word.get("comparative", "masculine", "accusative", "plural") == "celeriores"
    assert word.get("comparative", "masculine", "genitive", "plural") == "celeriorum"
    assert word.get("comparative", "masculine", "dative", "plural") == "celerioribus"
    assert word.get("comparative", "masculine", "ablative", "plural") == "celerioribus"

    assert word.get("comparative", "feminine", "nominative", "singular") == "celerior"
    assert word.get("comparative", "feminine", "vocative", "singular") == "celerior"
    assert word.get("comparative", "feminine", "accusative", "singular") == "celeriorem"
    assert word.get("comparative", "feminine", "genitive", "singular") == "celerioris"
    assert word.get("comparative", "feminine", "dative", "singular") == "celeriori"
    assert word.get("comparative", "feminine", "ablative", "singular") == "celeriore"
    assert word.get("comparative", "feminine", "nominative", "plural") == "celeriores"
    assert word.get("comparative", "feminine", "vocative", "plural") == "celeriores"
    assert word.get("comparative", "feminine", "accusative", "plural") == "celeriores"
    assert word.get("comparative", "feminine", "genitive", "plural") == "celeriorum"
    assert word.get("comparative", "feminine", "dative", "plural") == "celerioribus"
    assert word.get("comparative", "feminine", "ablative", "plural") == "celerioribus"

    assert word.get("comparative", "neuter", "nominative", "singular") == "celerius"
    assert word.get("comparative", "neuter", "vocative", "singular") == "celerius"
    assert word.get("comparative", "neuter", "accusative", "singular") == "celerius"
    assert word.get("comparative", "neuter", "genitive", "singular") == "celerioris"
    assert word.get("comparative", "neuter", "dative", "singular") == "celeriori"
    assert word.get("comparative", "neuter", "ablative", "singular") == "celeriore"
    assert word.get("comparative", "neuter", "nominative", "plural") == "celeriora"
    assert word.get("comparative", "neuter", "vocative", "plural") == "celeriora"
    assert word.get("comparative", "neuter", "accusative", "plural") == "celeriora"
    assert word.get("comparative", "neuter", "genitive", "plural") == "celeriorum"
    assert word.get("comparative", "neuter", "dative", "plural") == "celerioribus"
    assert word.get("comparative", "neuter", "ablative", "plural") == "celerioribus"

    assert (
        word.get("superlative", "masculine", "nominative", "singular") == "celerrimus"
    )
    assert word.get("superlative", "masculine", "vocative", "singular") == "celerrime"
    assert (
        word.get("superlative", "masculine", "accusative", "singular") == "celerrimum"
    )
    assert word.get("superlative", "masculine", "genitive", "singular") == "celerrimi"
    assert word.get("superlative", "masculine", "dative", "singular") == "celerrimo"
    assert word.get("superlative", "masculine", "ablative", "singular") == "celerrimo"
    assert word.get("superlative", "masculine", "nominative", "plural") == "celerrimi"
    assert word.get("superlative", "masculine", "vocative", "plural") == "celerrimi"
    assert word.get("superlative", "masculine", "accusative", "plural") == "celerrimos"
    assert word.get("superlative", "masculine", "genitive", "plural") == "celerrimorum"
    assert word.get("superlative", "masculine", "dative", "plural") == "celerrimis"
    assert word.get("superlative", "masculine", "ablative", "plural") == "celerrimis"

    assert word.get("superlative", "feminine", "nominative", "singular") == "celerrima"
    assert word.get("superlative", "feminine", "vocative", "singular") == "celerrima"
    assert word.get("superlative", "feminine", "accusative", "singular") == "celerrimam"
    assert word.get("superlative", "feminine", "genitive", "singular") == "celerrimae"
    assert word.get("superlative", "feminine", "dative", "singular") == "celerrimae"
    assert word.get("superlative", "feminine", "ablative", "singular") == "celerrima"
    assert word.get("superlative", "feminine", "nominative", "plural") == "celerrimae"
    assert word.get("superlative", "feminine", "vocative", "plural") == "celerrimae"
    assert word.get("superlative", "feminine", "accusative", "plural") == "celerrimas"
    assert word.get("superlative", "feminine", "genitive", "plural") == "celerrimarum"
    assert word.get("superlative", "feminine", "dative", "plural") == "celerrimis"
    assert word.get("superlative", "feminine", "ablative", "plural") == "celerrimis"

    assert word.get("superlative", "neuter", "nominative", "singular") == "celerrimum"
    assert word.get("superlative", "neuter", "vocative", "singular") == "celerrimum"
    assert word.get("superlative", "neuter", "accusative", "singular") == "celerrimum"
    assert word.get("superlative", "neuter", "genitive", "singular") == "celerrimi"
    assert word.get("superlative", "neuter", "dative", "singular") == "celerrimo"
    assert word.get("superlative", "neuter", "ablative", "singular") == "celerrimo"
    assert word.get("superlative", "neuter", "nominative", "plural") == "celerrima"
    assert word.get("superlative", "neuter", "vocative", "plural") == "celerrima"
    assert word.get("superlative", "neuter", "accusative", "plural") == "celerrima"
    assert word.get("superlative", "neuter", "genitive", "plural") == "celerrimorum"
    assert word.get("superlative", "neuter", "dative", "plural") == "celerrimis"
    assert word.get("superlative", "neuter", "ablative", "plural") == "celerrimis"
