# Auto-generated by monkeytype

from typing import (
    Any,
    Dict,
    Tuple,
)

class InflectionLUCodec:
    @classmethod
    def fromString(cls, line: str) -> Any: ...
    @classmethod
    def load(
        cls, fn: str
    ) -> Dict[
        str,
        Dict[
            str,
            Tuple[str, ...],
        ],
    ]: ...
    @staticmethod
    def updateForAuxMod(
        d: Dict[
            str,
            Dict[str, Tuple[str, ...]],
        ],
    ) -> Dict[
        str,
        Dict[str, Tuple[str, ...]],
    ]: ...
