# Auto-generated by stubgen

from _typeshed import Incomplete

class Entry:
    infl: Incomplete
    category: Incomplete
    source: Incomplete
    lemma: Incomplete
    def __init__(
        self,
        infl: Incomplete,
        category: Incomplete,
        source: Incomplete,
        lemma: Incomplete,
    ) -> None: ...

class LemmaTCorpFileCodec:
    @staticmethod
    def fromString(line: Incomplete) -> Incomplete: ...
    @staticmethod
    def toString(
        infl: Incomplete,
        category: Incomplete,
        source: Incomplete,
        lemma: Incomplete,
    ) -> Incomplete: ...
    @classmethod
    def load(cls: Incomplete, fn: Incomplete) -> Incomplete: ...
