# Auto-generated by monkeytype

from typing import Dict, Iterable, Tuple, Union

class LemmaLUCodec:
    @staticmethod
    def fromString(
        line: str,
    ) -> Union[
        Tuple[str, str, Tuple[str, str, str]],
        Tuple[str, str, Tuple[str]],
        Tuple[str, str, Tuple[str, str]],
    ]: ...
    @classmethod
    def load(
        cls, fn: str
    ) -> Dict[
        str,
        Dict[str, Union[Tuple[str, str], Tuple[str], Tuple[str, str, str]]],
    ]: ...
    @staticmethod
    def toString(word: str, category: str, forms: Iterable) -> str: ...  # type: ignore
