# Auto-generated by monkeytype

from typing import (
    Dict,
    Tuple,
)

class OverridesCodec:
    @staticmethod
    def load(fn: str) -> Dict[str, Dict[str, Tuple[str]]]: ...
    @staticmethod
    def toString(word_in: str, pos: str, word_out: str) -> str: ...
