from _typeshed import Incomplete

from nltk.util import (
    LazyConcatenation as LazyConcatenation,
)
from nltk.util import (
    LazyMap as LazyMap,
)

def accuracy(reference: Incomplete, test: Incomplete) -> Incomplete: ...
def precision(reference: Incomplete, test: Incomplete) -> Incomplete: ...
def recall(reference: Incomplete, test: Incomplete) -> Incomplete: ...
def f_measure(
    reference: Incomplete, test: Incomplete, alpha: float = 0.5
) -> Incomplete: ...
def log_likelihood(reference: Incomplete, test: Incomplete) -> Incomplete: ...
def approxrand(
    a: Incomplete, b: Incomplete, **kwargs: Incomplete
) -> Incomplete: ...
def demo() -> None: ...
