# Auto-generated by stubgen

from .models import (
    Parameters,
    Card,
    Rating,
    ReviewLog,
    SchedulingCards,
    SchedulingInfo,
)
from typing import Tuple
from datetime import datetime

class FSRS:
    p: Parameters
    DECAY: float
    FACTOR: float
    def __init__(
        self,
        w: Tuple[float, ...] | None = None,
        request_retention: float | None = None,
        maximum_interval: int | None = None,
    ) -> None: ...
    def review_card(
        self, card: Card, rating: Rating, now: datetime | None = None
    ) -> tuple[Card, ReviewLog]: ...
    def repeat(
        self, card: Card, now: datetime | None = None
    ) -> dict[int, SchedulingInfo]: ...
    def init_ds(self, s: SchedulingCards) -> None: ...
    def next_ds(
        self,
        s: SchedulingCards,
        last_d: float,
        last_s: float,
        retrievability: float,
    ) -> None: ...
    def init_stability(self, r: int) -> float: ...
    def init_difficulty(self, r: int) -> float: ...
    def forgetting_curve(
        self, elapsed_days: int, stability: float
    ) -> float: ...
    def next_interval(self, s: float) -> int: ...
    def next_difficulty(self, d: float, r: int) -> float: ...
    def mean_reversion(self, init: float, current: float) -> float: ...
    def next_recall_stability(
        self, d: float, s: float, r: float, rating: int
    ) -> float: ...
    def next_forget_stability(self, d: float, s: float, r: float) -> float: ...
