from _typeshed import Incomplete

from nltk.twitter import (
    Query as Query,
)
from nltk.twitter import (
    Streamer as Streamer,
)
from nltk.twitter import (
    TweetViewer as TweetViewer,
)
from nltk.twitter import (
    TweetWriter as TweetWriter,
)
from nltk.twitter import (
    Twitter as Twitter,
)
from nltk.twitter import (
    credsfromfile as credsfromfile,
)

SPACER: str

def verbose(func: Incomplete) -> Incomplete: ...
def yesterday() -> Incomplete: ...
def setup() -> None: ...
def twitterclass_demo() -> None: ...
def sampletoscreen_demo(limit: int = 20) -> None: ...
def tracktoscreen_demo(
    track: str = "taylor swift", limit: int = 10
) -> None: ...
def search_demo(keywords: str = "nltk") -> None: ...
def tweets_by_user_demo(user: str = "NLTK_org", count: int = 200) -> None: ...
def lookup_by_userid_demo() -> None: ...
def followtoscreen_demo(limit: int = 10) -> None: ...
def streamtofile_demo(limit: int = 20) -> None: ...
def limit_by_time_demo(keywords: str = "nltk") -> None: ...
def corpusreader_demo() -> None: ...
def expand_tweetids_demo() -> None: ...

ALL: Incomplete
DEMOS: Incomplete
