from _typeshed import Incomplete

from nltk.data import load as load
from nltk.stem.api import StemmerI as StemmerI

class RSLPStemmer(StemmerI):
    def __init__(self) -> None: ...
    def read_rule(self, filename: Incomplete) -> Incomplete: ...
    def stem(self, word: Incomplete) -> Incomplete: ...
    def apply_rule(
        self, word: Incomplete, rule_index: Incomplete
    ) -> Incomplete: ...
