from _typeshed import Incomplete

def selection(a: Incomplete) -> Incomplete: ...
def bubble(a: Incomplete) -> Incomplete: ...
def merge(a: Incomplete) -> Incomplete: ...
def quick(a: Incomplete) -> Incomplete: ...
def demo() -> None: ...
