from _typeshed import Incomplete

from nltk.probability import (
    ConditionalFreqDist as ConditionalFreqDist,
)
from nltk.probability import (
    FreqDist as FreqDist,
)

class NgramCounter:
    def __init__(self, ngram_text: Incomplete | None = None) -> None: ...
    def update(self, ngram_text: Incomplete) -> None: ...
    def N(self) -> Incomplete: ...
    def __getitem__(self, item: Incomplete) -> Incomplete: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: Incomplete) -> bool: ...
