import threading

from _typeshed import Incomplete

from nltk.corpus import alpino as alpino
from nltk.corpus import brown as brown
from nltk.corpus import cess_cat as cess_cat
from nltk.corpus import cess_esp as cess_esp
from nltk.corpus import floresta as floresta
from nltk.corpus import indian as indian
from nltk.corpus import mac_morpho as mac_morpho
from nltk.corpus import machado as machado
from nltk.corpus import nps_chat as nps_chat
from nltk.corpus import sinica_treebank as sinica_treebank
from nltk.corpus import treebank as treebank
from nltk.probability import FreqDist as FreqDist
from nltk.util import in_idle as in_idle

CORPUS_LOADED_EVENT: str
ERROR_LOADING_CORPUS_EVENT: str
POLL_INTERVAL: int

class CollocationsView:
    queue: Incomplete
    model: Incomplete
    top: Incomplete
    after: Incomplete
    def __init__(self) -> None: ...
    def set_result_size(self, **kwargs: Incomplete) -> None: ...
    current_page: int
    def reset_current_page(self) -> None: ...
    def handle_error_loading_corpus(self, event: Incomplete) -> None: ...
    def handle_corpus_loaded(self, event: Incomplete) -> None: ...
    def corpus_selected(self, *args: Incomplete) -> None: ...
    def previous(self) -> None: ...
    def __next__(self) -> None: ...
    def load_corpus(self, selection: Incomplete) -> None: ...
    def freeze_editable(self) -> None: ...
    def clear_results_box(self) -> None: ...
    def fire_event(self, event: Incomplete) -> None: ...
    def destroy(self, *e: Incomplete) -> None: ...
    def mainloop(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def unfreeze_editable(self) -> None: ...
    def set_paging_button_states(self) -> None: ...
    def write_results(self, results: Incomplete) -> None: ...

class CollocationsModel:
    result_count: Incomplete
    selected_corpus: Incomplete
    collocations: Incomplete
    CORPORA: Incomplete
    DEFAULT_CORPUS: Incomplete
    queue: Incomplete
    def __init__(self, queue: Incomplete) -> None: ...
    result_pages: Incomplete
    results_returned: int
    def reset_results(self) -> None: ...
    def load_corpus(self, name: Incomplete) -> None: ...
    def non_default_corpora(self) -> Incomplete: ...
    def is_last_page(self, number: Incomplete) -> Incomplete: ...
    def next(self, page: Incomplete) -> Incomplete: ...
    def prev(self, page: Incomplete) -> Incomplete: ...
    class LoadCorpus(threading.Thread):
        def __init__(self, name: Incomplete, model: Incomplete) -> None: ...
        def run(self) -> None: ...

def app() -> None: ...
