__all__ = ["decorator", "new_wrapper", "getinfo"]
from _typeshed import Incomplete

def getinfo(func: Incomplete) -> Incomplete: ...
def new_wrapper(wrapper: Incomplete, model: Incomplete) -> Incomplete: ...
def decorator(caller: Incomplete) -> Incomplete: ...
