from _typeshed import Incomplete

from nltk.data import find as find

def brown_tagset(tagpattern: Incomplete | None = None) -> None: ...
def claws5_tagset(tagpattern: Incomplete | None = None) -> None: ...
def upenn_tagset(tagpattern: Incomplete | None = None) -> None: ...
