from _typeshed import Incomplete

class Reduce:
    reduction: Incomplete
    def __new__(cls, *reduction, **kwargs): ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...
    def __reduce__(self): ...
    def __reduce_ex__(self, protocol): ...

class _CallableReduce(Reduce):
    def __call__(self, *args, **kwargs): ...

def Getattr(object, name, default=...): ...
def move_to(module, name: Incomplete | None = None): ...
def register_shim(name, default): ...
