from gzip import GzipFile

class DataContainer:
    def __init__(self, obj: object | None = None) -> None: ...
    def save(self, filename: str) -> None: ...
    @staticmethod
    def _open(filename: str, mode: str) -> GzipFile: ...
    @classmethod
    def load(cls: object, filename: str) -> DataContainer: ...
