# Verbs
THIRD_IO_VERBS = [
    "accipio",
    "capio",
    "conspicio",
    "cupio",
    "facio",
    "fugio",
    "iacio",
    "interficio",
    "rapio",
    "respicio",
]

IRREGULAR_VERBS = {
    "sum": {
        "Vpreactindsg1": "sum",
        "Vpreactindsg2": "es",
        "Vpreactindsg3": "est",
        "Vpreactindpl1": "sumus",
        "Vpreactindpl2": "estis",
        "Vpreactindpl3": "sunt",
        "Vimpactindsg1": "eram",
        "Vimpactindsg2": "eras",
        "Vimpactindsg3": "erat",
        "Vimpactindpl1": "eramus",
        "Vimpactindpl2": "eratis",
        "Vimpactindpl3": "erant",
        "Vperactindsg1": "fui",
        "Vperactindsg2": "fuisti",
        "Vperactindsg3": "fuit",
        "Vperactindpl1": "fuimus",
        "Vperactindpl2": "fuistis",
        "Vperactindpl3": "fuerunt",
        "Vplpactindsg1": "fueram",
        "Vplpactindsg2": "fueras",
        "Vplpactindsg3": "fuerat",
        "Vplpactindpl1": "fueramus",
        "Vplpactindpl2": "fueratis",
        "Vplpactindpl3": "fuerant",
        "Vpreactinf   ": "esse",
        "Vimpactsbjsg1": "essem",
        "Vimpactsbjsg2": "esses",
        "Vimpactsbjsg3": "esset",
        "Vimpactsbjpl1": "essemus",
        "Vimpactsbjpl2": "essetis",
        "Vimpactsbjpl3": "essent",
        "Vplpactsbjsg1": "fuissem",
        "Vplpactsbjsg2": "fuisses",
        "Vplpactsbjsg3": "fuisset",
        "Vplpactsbjpl1": "fuissemus",
        "Vplpactsbjpl2": "fuissetis",
        "Vplpactsbjpl3": "fuissent",
    },
    "possum": {
        "Vpreactindsg1": "possum",
        "Vpreactindsg2": "potes",
        "Vpreactindsg3": "potest",
        "Vpreactindpl1": "possumus",
        "Vpreactindpl2": "potestis",
        "Vpreactindpl3": "possunt",
        "Vimpactindsg1": "poteram",
        "Vimpactindsg2": "poteras",
        "Vimpactindsg3": "poterat",
        "Vimpactindpl1": "poteramus",
        "Vimpactindpl2": "poteratis",
        "Vimpactindpl3": "poterant",
        "Vperactindsg1": "potui",
        "Vperactindsg2": "potuisti",
        "Vperactindsg3": "potuit",
        "Vperactindpl1": "potuimus",
        "Vperactindpl2": "potuistis",
        "Vperactindpl3": "potuerunt",
        "Vplpactindsg1": "potueram",
        "Vplpactindsg2": "potueras",
        "Vplpactindsg3": "potuerat",
        "Vplpactindpl1": "potueramus",
        "Vplpactindpl2": "potueratis",
        "Vplpactindpl3": "potuerant",
        "Vpreactinf   ": "posse",
        "Vimpactsbjsg1": "possem",
        "Vimpactsbjsg2": "posses",
        "Vimpactsbjsg3": "posset",
        "Vimpactsbjpl1": "possemus",
        "Vimpactsbjpl2": "possetis",
        "Vimpactsbjpl3": "possent",
        "Vplpactsbjsg1": "potuissem",
        "Vplpactsbjsg2": "potuisses",
        "Vplpactsbjsg3": "potuisset",
        "Vplpactsbjpl1": "potuissemus",
        "Vplpactsbjpl2": "potuissetis",
        "Vplpactsbjpl3": "potuissent",
    },
    "fero": {
        "Vpreactindsg1": "fero",
        "Vpreactindsg2": "fers",
        "Vpreactindsg3": "fert",
        "Vpreactindpl1": "ferimus",
        "Vpreactindpl2": "fertis",
        "Vpreactindpl3": "ferunt",
        "Vimpactindsg1": "ferebam",
        "Vimpactindsg2": "ferebas",
        "Vimpactindsg3": "ferebat",
        "Vimpactindpl1": "ferebamus",
        "Vimpactindpl2": "ferebatis",
        "Vimpactindpl3": "ferebant",
        "Vperactindsg1": "tuli",
        "Vperactindsg2": "tulisti",
        "Vperactindsg3": "tulit",
        "Vperactindpl1": "tulimus",
        "Vperactindpl2": "tulistis",
        "Vperactindpl3": "tulerunt",
        "Vplpactindsg1": "tuleram",
        "Vplpactindsg2": "tuleras",
        "Vplpactindsg3": "tulerat",
        "Vplpactindpl1": "tuleramus",
        "Vplpactindpl2": "tuleratis",
        "Vplpactindpl3": "tulerant",
        "Vpreactinf   ": "ferre",
        "Vpreactipesg2": "fer",
        "Vpreactipepl2": "ferte",
        "Vimpactsbjsg1": "ferrem",
        "Vimpactsbjsg2": "ferres",
        "Vimpactsbjsg3": "ferret",
        "Vimpactsbjpl1": "ferremus",
        "Vimpactsbjpl2": "ferretis",
        "Vimpactsbjpl3": "ferrent",
        "Vplpactsbjsg1": "tulissem",
        "Vplpactsbjsg2": "tulisses",
        "Vplpactsbjsg3": "tulisset",
        "Vplpactsbjpl1": "tulissemus",
        "Vplpactsbjpl2": "tulissetis",
        "Vplpactsbjpl3": "tulissent",
    },
    "eo": {
        "Vpreactindsg1": "eo",
        "Vpreactindsg2": "is",
        "Vpreactindsg3": "t",
        "Vpreactindpl1": "imus",
        "Vpreactindpl2": "itis",
        "Vpreactindpl3": "eunt",
        "Vimpactindsg1": "ibam",
        "Vimpactindsg2": "ibas",
        "Vimpactindsg3": "ibat",
        "Vimpactindpl1": "ibamus",
        "Vimpactindpl2": "ibatis",
        "Vimpactindpl3": "ibant",
        "Vperactindsg1": "ii",
        "Vperactindsg2": "iisti",
        "Vperactindsg3": "iit",
        "Vperactindpl1": "iimus",
        "Vperactindpl2": "iistis",
        "Vperactindpl3": "ierunt",
        "Vplpactindsg1": "ieram",
        "Vplpactindsg2": "ieras",
        "Vplpactindsg3": "ierat",
        "Vplpactindpl1": "ieramus",
        "Vplpactindpl2": "ieratis",
        "Vplpactindpl3": "ierant",
        "Vpreactinf   ": "ire",
        "Vpreactipesg2": "i",
        "Vpreactipepl2": "ite",
        "Vimpactsbjsg1": "irem",
        "Vimpactsbjsg2": "ires",
        "Vimpactsbjsg3": "iret",
        "Vimpactsbjpl1": "iremus",
        "Vimpactsbjpl2": "iretis",
        "Vimpactsbjpl3": "irent",
        "Vplpactsbjsg1": "iissem",
        "Vplpactsbjsg2": "iisses",
        "Vplpactsbjsg3": "iisset",
        "Vplpactsbjpl1": "iissemus",
        "Vplpactsbjpl2": "iissetis",
        "Vplpactsbjpl3": "iissent",
    },
}

# TODO: finish this
IRREGULAR_NOUNS = {
    "ego": {
        "sg": ["ego", "ego", "me", "mei", "mihi", "me"],
        "pl": ["nos", "nos", "nos", "nostri/nostrum", "nobis", "nobis"],
    },
    "tu": {"sg": ["tu", ""]},
}
