# Auto-generated by stubgen

from _typeshed import Incomplete

from .KerasModel import KerasModel as KerasModel
from .KerasModel import limitTFMem as limitTFMem

class ModelLemma(KerasModel):
    def __init__(self) -> None: ...
    model: Incomplete
    def create(
        self,
        input_len: Incomplete,
        input_letters: Incomplete,
        output_rules: Incomplete,
    ) -> None: ...
    def train(
        self,
        xdata: Incomplete,
        ydata: Incomplete,
        batch_size: Incomplete,
        nepochs: Incomplete,
        **kwargs: Incomplete,
    ) -> None: ...
