# Auto-generated by stubgen

from typing import Any

import numpy as np
from _typeshed import Incomplete

from ..codecs.LemmaTCorpFileCodec import (
    LemmaTCorpFileCodec as LemmaTCorpFileCodec,
)
from ..slexicon.SKey import *  # noqa: F403

class ModelLemmaInData:
    WVEC_LEN: int
    MAX_LETTER_IDX: int
    entries: Incomplete
    def __init__(self, fn: Incomplete) -> None: ...
    @classmethod
    def wordToVec(
        cls: object, word: str, category: str
    ) -> np.ndarray[Any, Any]: ...
    @staticmethod
    def getLetterClasses() -> list[str]: ...
