from _typeshed import Incomplete

from nltk.corpus import bcp47 as bcp47

codepattern: Incomplete

def langname(tag: Incomplete, typ: str = "full") -> Incomplete: ...
def langcode(name: Incomplete, typ: int = 2) -> Incomplete: ...
def tag2q(tag: Incomplete) -> Incomplete: ...
def q2tag(qcode: Incomplete) -> Incomplete: ...
def q2name(qcode: Incomplete, typ: str = "full") -> Incomplete: ...
def lang2q(name: Incomplete) -> Incomplete: ...
def inverse_dict(dic: Incomplete) -> Incomplete: ...

wiki_bcp47: Incomplete
iso639short: Incomplete
iso639retired: Incomplete
iso639long: Incomplete
iso639code_retired: Incomplete
