from collections.abc import Generator

from _typeshed import Incomplete

class TgrepException(Exception): ...

def ancestors(node: Incomplete) -> Incomplete: ...
def unique_ancestors(node: Incomplete) -> Incomplete: ...
def tgrep_tokenize(tgrep_string: Incomplete) -> Incomplete: ...
def tgrep_compile(tgrep_string: Incomplete) -> Incomplete: ...
def treepositions_no_leaves(tree: Incomplete) -> Incomplete: ...
def tgrep_positions(
    pattern: Incomplete, trees: Incomplete, search_leaves: bool = True
) -> Generator[Incomplete, None, None]: ...
def tgrep_nodes(
    pattern: Incomplete, trees: Incomplete, search_leaves: bool = True
) -> Generator[Incomplete, None, None]: ...
