# Auto-generated by stubgen

data_repo: str
proj_resources: str
gutenberg_dir: str
bwcorp_dir: str
unigrams_gb_all_fn: str
unigrams_gb_clean_fn: str
unigrams_bw_all_fn: str
unigrams_bw_clean_fn: str
unigrams_fn: str
english_dict_fn: str
lexicon_fn: str
ftable_fn: str
lemma_lu_fn: str
inflection_lu_fn: str
model_lemma_cl_fn: str
lemma_tcorp_fn: str
infl_tcorp_fn: str
model_lemma_fn: str
model_infl_fn: str
lemma_overrides_fn: str
infl_overrides_fn: str
acc_word_set_fn: str
acc_lemma_corp_fn: str
kinfer_type: str
