from _typeshed import Incomplete

def str2tuple(s: Incomplete, sep: str = "/") -> Incomplete: ...
def tuple2str(tagged_token: Incomplete, sep: str = "/") -> Incomplete: ...
def untag(tagged_sentence: Incomplete) -> Incomplete: ...
