name: check
on:
  push:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13.0"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: "recursive"

      # - name: Cache tox folder
      #   id: cache-tox
      #   uses: actions/cache@v4.1.1
      #   with:
      #     path: ".tox"
      #     key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml','tox.ini','poetry.lock') }}

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.py }}

      - name: Create testdump directory
        run: mkdir tests/python_src_lego/test_vocab_files/testdump

      - name: Install tox
        run: python -m pip install tox-gh>=1.2

      - name: Setup test suite
        # if: steps.cache-tox.outputs.cache-hit != 'true'
        run: tox -vv --notest

      - name: Run test suite
        run: tox --skip-pkg-install
