name: check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13.0-rc.3"
          - "3.12.7"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Cache tox folder
        id: cache-tox
        uses: actions/cache@v4.1.0
        with:
          path: ".tox"
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml','tox.ini') }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.5
        with:
          version: "18.1.8"

      - name: Install libtinfo5 (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5


      - name: Symlink libtinfo.so (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.1 ${{ env.LLVM_PATH }}/lib/libtinfo.so
          sudo ln -sf libtinfo-18.so.1 /lib/x86_64-linux-gnu/libtinfo.so
        working-directory: ${{ env.LLVM_PATH }}/lib

      - name: Compile cpp code
        run: clang++ -shared -fPIC -o python_src/lego/libkey.so python_src/lego/key/key.cpp

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.py }}

      - name: Create testdump directory
        run: mkdir tests/python_src_lego/test_vocab_files/testdump

      - name: Install tox
        run: python -m pip install tox-gh>=1.2

      - name: Setup test suite
        if: steps.cache-tox.outputs.cache-hit != 'true'
        run: tox -vv --notest

      - name: Run test suite
        run: tox --skip-pkg-install
