name: check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13.0-rc.1"
          - "3.12.5"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Compile cpp code
        run: clang++ -shared -fPIC -o python_src/lego/libkey.so python_src/lego/key/key.cpp

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Create testdump directory
        run: mkdir tests/python_src_lego/test_vocab_files/testdump

      - name: Install tox
        run: python -m pip install tox-gh>=1.2

      - name: Setup test suite
        run: tox -vv --notest

      - name: Run test suite
        run: tox --skip-pkg-install
