name: interrogate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: Test docstring coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13.0"
        os:
          - ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.py }}

      - name: Run interrogate
        uses: rduo1009/python-interrogate-check@main
        with:
          path: "src"
          badge-location: "docs/assets/interrogate_badge.svg"
        continue-on-error: true

      - name: Setup git
        uses: qoomon/actions--setup-git@v1.1.1
        with:
          user: bot

      - name: Commit files
        run: |
          git add docs/assets/interrogate_badge.svg
          git diff --exit-code || git commit -m "🧹 chore: update interrogate badge" -a
          git push
