from _typeshed import Incomplete

def get_words_from_dictionary(lemmas: Incomplete) -> Incomplete: ...

class Paice:
    lemmas: Incomplete
    stems: Incomplete
    coords: Incomplete
    errt: Incomplete
    def __init__(self, lemmas: Incomplete, stems: Incomplete) -> None: ...
    def update(self) -> None: ...

def demo() -> None: ...
