#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""A package that generates questions about Latin vocabulary, from a
VocabList object generated by lego.
"""

from . import question_classes

__all__ = ["question_classes"]
