"""A package that generates questions about Latin vocabulary, from a
VocabList object generated by lego.
"""  # noqa: D205

from . import asker, exceptions, question_classes, rules, type_aliases

__all__ = ["asker", "exceptions", "question_classes", "rules", "type_aliases"]
