"""Contains type aliases used by rogo."""

from typing import ReadOnly, TypedDict

from .. import accido

type Vocab = list[accido.endings._Word]  # noqa: SLF001

Settings = TypedDict(
    "Settings",
    {
        "exclude-verb-present-active-indicative": ReadOnly[bool],
        "exclude-verb-imperfect-active-indicative": ReadOnly[bool],
        "exclude-verb-perfect-active-indicative": ReadOnly[bool],
        "exclude-verb-pluperfect-active-indicative": ReadOnly[bool],
        "exclude-verb-present-active-infinitive": ReadOnly[bool],
        "exclude-verb-present-active-imperative": ReadOnly[bool],
        "exclude-verb-imperfect-active-subjunctive": ReadOnly[bool],
        "exclude-verb-pluperfect-active-subjunctive": ReadOnly[bool],
        "exclude-verb-singular": ReadOnly[bool],
        "exclude-verb-plural": ReadOnly[bool],
        "exclude-verb-1st-person": ReadOnly[bool],
        "exclude-verb-2nd-person": ReadOnly[bool],
        "exclude-verb-3rd-person": ReadOnly[bool],
        "exclude-participles": ReadOnly[bool],
        "exclude-participle-present-active": ReadOnly[bool],
        "exclude-participle-perfect-passive": ReadOnly[bool],
        "exclude-participle-masculine": ReadOnly[bool],
        "exclude-participle-feminine": ReadOnly[bool],
        "exclude-participle-neuter": ReadOnly[bool],
        "exclude-participle-nominative": ReadOnly[bool],
        "exclude-participle-vocative": ReadOnly[bool],
        "exclude-participle-accusative": ReadOnly[bool],
        "exclude-participle-genitive": ReadOnly[bool],
        "exclude-participle-dative": ReadOnly[bool],
        "exclude-participle-ablative": ReadOnly[bool],
        "exclude-participle-singular": ReadOnly[bool],
        "exclude-participle-plural": ReadOnly[bool],
        "exclude-noun-nominative": ReadOnly[bool],
        "exclude-noun-vocative": ReadOnly[bool],
        "exclude-noun-accusative": ReadOnly[bool],
        "exclude-noun-genitive": ReadOnly[bool],
        "exclude-noun-dative": ReadOnly[bool],
        "exclude-noun-ablative": ReadOnly[bool],
        "exclude-noun-singular": ReadOnly[bool],
        "exclude-noun-plural": ReadOnly[bool],
        "exclude-adjective-masculine": ReadOnly[bool],
        "exclude-adjective-feminine": ReadOnly[bool],
        "exclude-adjective-neuter": ReadOnly[bool],
        "exclude-adjective-nominative": ReadOnly[bool],
        "exclude-adjective-vocative": ReadOnly[bool],
        "exclude-adjective-accusative": ReadOnly[bool],
        "exclude-adjective-genitive": ReadOnly[bool],
        "exclude-adjective-dative": ReadOnly[bool],
        "exclude-adjective-ablative": ReadOnly[bool],
        "exclude-adjective-singular": ReadOnly[bool],
        "exclude-adjective-plural": ReadOnly[bool],
        "exclude-adjective-positive": ReadOnly[bool],
        "exclude-adjective-comparative": ReadOnly[bool],
        "exclude-adjective-superlative": ReadOnly[bool],
        "exclude-adverbs": ReadOnly[bool],
        "exclude-adverb-positive": ReadOnly[bool],
        "exclude-adverb-comparative": ReadOnly[bool],
        "exclude-adverb-superlative": ReadOnly[bool],
        "exclude-pronoun-masculine": ReadOnly[bool],
        "exclude-pronoun-feminine": ReadOnly[bool],
        "exclude-pronoun-neuter": ReadOnly[bool],
        "exclude-pronoun-nominative": ReadOnly[bool],
        "exclude-pronoun-vocative": ReadOnly[bool],
        "exclude-pronoun-accusative": ReadOnly[bool],
        "exclude-pronoun-genitive": ReadOnly[bool],
        "exclude-pronoun-dative": ReadOnly[bool],
        "exclude-pronoun-ablative": ReadOnly[bool],
        "exclude-pronoun-singular": ReadOnly[bool],
        "exclude-pronoun-plural": ReadOnly[bool],
        "exclude-nouns": ReadOnly[bool],
        "exclude-verbs": ReadOnly[bool],
        "exclude-adjectives": ReadOnly[bool],
        "exclude-pronouns": ReadOnly[bool],
        "exclude-regulars": ReadOnly[bool],
        "exclude-verb-first-conjugation": ReadOnly[bool],
        "exclude-verb-second-conjugation": ReadOnly[bool],
        "exclude-verb-third-conjugation": ReadOnly[bool],
        "exclude-verb-fourth-conjugation": ReadOnly[bool],
        "exclude-verb-thirdio-conjugation": ReadOnly[bool],
        "exclude-verb-irregular-conjugation": ReadOnly[bool],
        "exclude-noun-first-declension": ReadOnly[bool],
        "exclude-noun-second-declension": ReadOnly[bool],
        "exclude-noun-third-declension": ReadOnly[bool],
        "exclude-noun-fourth-declension": ReadOnly[bool],
        "exclude-noun-fifth-declension": ReadOnly[bool],
        "exclude-noun-irregular-declension": ReadOnly[bool],
        "exclude-adjective-212-declension": ReadOnly[bool],
        "exclude-adjective-third-declension": ReadOnly[bool],
        "include-typein-engtolat": ReadOnly[bool],
        "include-typein-lattoeng": ReadOnly[bool],
        "include-parse": ReadOnly[bool],
        "include-inflect": ReadOnly[bool],
        "include-principal-parts": ReadOnly[bool],
        "include-multiplechoice-engtolat": ReadOnly[bool],
        "include-multiplechoice-lattoeng": ReadOnly[bool],
        "number-multiplechoice-options": ReadOnly[int],
    },
)
